DROP SCHEMA public CASCADE;

CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE PERSON (
   id BIGINT NOT NULL PRIMARY KEY,
   firstname VARCHAR(255) NOT NULL,
   lastname VARCHAR(255) NOT NULL,
   code VARCHAR(100) NOT NULL,
   customerType VARCHAR(255)
);

CREATE TABLE PHONE (
   id BIGINT NOT NULL PRIMARY KEY,
   Type VARCHAR(255) NOT NULL,
   Value VARCHAR(255) NOT NULL,
);